Updated script to only tag in master.

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -7,16 +7,34 @@ project_type: xamarin
 workflows:
   ci:
     steps:
-    - script@1.1.4:
+    - script:
+        run_if: '{{getenv "BITRISE_GIT_BRANCH" | eq "master"}}'
         inputs:
         - content: |-
             #!/bin/bash
             # fail if any commands fails and debug log
-            set -ex            
-
-            # build script
+            set -ex
+   
             ./build.sh -v diagnostic -t Publish-NuGetPackage
-    - deploy-to-bitrise-io@1.3.6: {}
+    - script:
+        run_if: '{{getenv "BITRISE_GIT_BRANCH" | eq "master"}}'
+        inputs:
+        - content: |-
+            #!/bin/bash
+            # fail if any commands fails and debug log
+            set -ex
+            
+            git tag $BITRISE_BUILD_NUMBER
+            git push --tags
+    - script:
+        run_if: '{{getenv "BITRISE_GIT_BRANCH" | ne "master"}}'
+        inputs:
+        - content: |-
+            #!/bin/bash
+            # fail if any commands fails and debug log
+            set -ex
+
+            ./build.sh -v diagnostic -t NuGet  
 app:
   envs:
   - BITRISE_DEPLOY_DIR: artifacts
